image: rocker/r-ver:4.4.2

before_script:
  - apt-get update
  - apt-get -y install pandoc libcurl4-openssl-dev r-cran-devtools r-cran-testthat r-cran-curl
  - R -e "install.packages('BiocManager'); BiocManager::install(version = '3.20')"
  - R -e "dir(); getwd(); sessionInfo(); install.packages('devtools'); install.packages('pkgdown'); BiocManager::install('MSA2dist'); devtools::install()"
  - R -e "setwd(paste0(find.package('CRBHits'), '/extdata/')); system(paste0('unzip last-1639.zip')); setwd(paste0(find.package('CRBHits'), '/extdata/last-1639/')); system('make')"
  - R -e "setwd(paste0(find.package('CRBHits'), '/extdata/')); system(paste0('tar -xvf KaKs_Calculator2.0_src.tar.gz')); setwd(paste0(find.package('CRBHits'), '/extdata/KaKs_Calculator2.0_src/src/')); system('make clean'); system('make')"
  - R -e "setwd(paste0(find.package('CRBHits'), '/extdata/')); system(paste0('unzip dagchainer.zip')); setwd(paste0(find.package('CRBHits'), '/extdata/dagchainer/')); system('make')"

pages:
  stage: deploy
  script:
    - R -e "dir(); getwd(); sessionInfo(); pkgdown::build_site()"
  artifacts:
    paths:
      - public
  only:
    - devel
