image: r-base

before_script:
  - apt-get update
  - apt-get -y install libcurl4-openssl-dev libssl-dev libxml2-dev libglu1-mesa-dev libssh2-1-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev libgit2-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev pandoc r-cran-devtools r-cran-testthat r-cran-curl r-cran-seqinr r-cran-ape r-cran-domc r-cran-foreach r-cran-tidyverse r-cran-mclust r-cran-ragg r-bioc-biostrings r-cran-uuid r-cran-ggplot2 r-cran-callr
  - R -e "dir()"
  - R -e "getwd()"
  - R -e "sessionInfo()"
  - R -e "install.packages('gridExtra',repos='http://cran.rstudio.com')"
  - R -e "install.packages('feature',repos='http://cran.rstudio.com')"
  - R -e "devtools::install_github('r-lib/ragg')"
  - R -e "devtools::install_github('r-lib/pkgdown')"
  - R -e "devtools::install_github('tidyverse/ggplot2')"
  - R -e "devtools::install_gitlab('mpievolbio-it/crbhits', host = 'https://gitlab.gwdg.de')"
  - R -e "setwd(paste0(find.package('CRBHits'), '/extdata/')); system(paste0('unzip last-1219.zip')); setwd(paste0(find.package('CRBHits'), '/extdata/last-1219/')); system('make')"
  - R -e "setwd(paste0(find.package('CRBHits'), '/extdata/')); system(paste0('tar -xvf KaKs_Calculator2.0.tar.gz')); setwd(paste0(find.package('CRBHits'), '/extdata/KaKs_Calculator2.0/src/')); system('make clean'); system('make')"
  - R -e "setwd(paste0(find.package('CRBHits'), '/extdata/')); system(paste0('unzip dagchainer.zip')); setwd(paste0(find.package('CRBHits'), '/extdata/dagchainer/')); system('make')"

pages:
  stage: deploy
  script:
    - R -e "dir()"
    - R -e "getwd()"
    - R -e "sessionInfo()"
    - R -e "devtools::document()"
    - R -e "usethis::use_pkgdown()"
    - R -e "pkgdown::build_site()"
  artifacts:
    paths:
      - public
  only:
    - master
