image: r-base

before_script:
  - apt-get update
  - apt-get -y install libcurl4-openssl-dev libssl-dev libxml2-dev pandoc libglu1-mesa-dev libssh2-1-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev r-cran-devtools r-cran-testthat r-cran-curl r-cran-seqinr r-cran-foreach r-cran-doMC r-cran-tidyverse r-cran-mclust r-cran-feature r-cran-pkgdown
  - R -e "dir()"
  - R -e "getwd()"
  - R -e "sessionInfo()"
  - R -e "if (!requireNamespace('BiocManager', quietly = TRUE)) {install.packages('BiocManager')}"
  - R -e "BiocManager::install('Biostrings')"
  - R -e "install.packages('pkgdown')"
  - R -e "devtools::install_gitlab('mpievolbio-it/crbhits', host = 'https://gitlab.gwdg.de')"
  - R -e "setwd(paste0(find.package('CRBHits'), '/extdata/')); system(paste0('unzip last-1133.zip')); setwd(paste0(find.package('CRBHits'), '/extdata/last-1133/')); system('make')"
  - R -e "setwd(paste0(find.package('CRBHits'), '/extdata/')); system(paste0('tar -xvf KaKs_Calculator2.0.tar.gz')); setwd(paste0(find.package('CRBHits'), '/extdata/KaKs_Calculator2.0/src/')); system('make clean'); system('make')"
  - R -e "setwd(paste0(find.package('CRBHits'), '/extdata/')); system(paste0('unzip dagchainer.zip')); setwd(paste0(find.package('CRBHits'), '/extdata/dagchainer/')); system('make')"

pages:
  stage: deploy
  script:
    - R -e "pkgdown::build_site()"
  artifacts:
    paths:
      - public
  only:
    - master
