before_script:
  - apt-get update && apt-get -y install pandoc r-base
  - R -e "install.packages('devtools',repos='http://cran.rstudio.com')"
  - R -e "install.packages('rmarkdown',repos='http://cran.rstudio.com')"
  - R -e "install.packages('seqinr',repos='http://cran.rstudio.com')"
  - R -e "install.packages('foreach',repos='http://cran.rstudio.com')"
  - R -e "install.packages('doMC',repos='http://cran.rstudio.com')"
  - R -e "install.packages('magrittr',repos='http://cran.rstudio.com')"
  - R -e "if (!requireNamespace('BiocManager', quietly = TRUE)) {install.packages('BiocManager')}
  - R -e "BiocManager::install('Biostrings')"
  - R -e "install.packages("pkgdown")"

pages:
  script:
    - R -e "pkgdown::build_site()"
  artifacts:
    paths:
      - public
  only:
    - master