language: r
cache: packages
warnings_are_errors: true
bioc_required: true
bioc_packages:
   - Biostrings
os: linux
dist: xenial
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libcurl4-openssl-dev libssl-dev libxml2-dev pandoc libglu1-mesa-dev
r_packages:
  - devtools
  - testthat
  - seqinr
  - foreach
  - doMC
  - magrittr
  - mclust
  - feature
r:
  - release
  - devel
