language: r
cache: packages
warnings_are_errors: true

r_packages:
  - devtools
  - testthat
  - seqinr
  - foreach
  - doMC
  - dplyr
  - tidyr
  - stringr
  - mclust
  - feature

bioc_required: true
bioc_packages:
   - DelayedArray
   - BiocGenerics
   - Biostrings

matrix:
  include:
    - name: linux-focal-r-release
      os: linux
      dist: focal
      r: release
      before_install:
        - sudo apt-get update
        - sudo apt-get -y install libcurl4-openssl-dev libssl-dev libxml2-dev pandoc libglu1-mesa-dev
      before_script:
        - R -e "sessionInfo()"
    - name: linux-focal-r-devel
      os: linux
      dist: focal
      r: devel
      before_install:
        - sudo apt-get update
        - sudo apt-get -y install libcurl4-openssl-dev libssl-dev libxml2-dev pandoc libglu1-mesa-dev
      before_script:
        - R -e "sessionInfo()"
    - name: osx-xcode12-r-release
      os: osx
      osx_image: xcode12
      r: release
      addons:
        homebrew:
          packages:
            - curl
            - openssl
            - xml2
            - mesa
