language: r
cache: packages
warnings_are_errors: true

r_packages:
  - devtools
  - testthat
  - seqinr
  - foreach
  - doMC
  - magrittr
  - mclust
  - feature

bioc_required: true
bioc_packages:
   - DelayedArray
   - BiocGenerics
   - Biostrings

matrix:
  include:
    - os: linux
      dist: bionic
      r:
        - release
        - devel
      before_install:
        - sudo apt-get update
        - sudo apt-get -y install libcurl4-openssl-dev libssl-dev libxml2-dev pandoc libglu1-mesa-dev
      before_script:
        - R -e "sessionInfo()"
    - os: osx
      osx_image: xcode12
      r:
        - release
        - devel
      addons:
        homebrew:
          packages:
            - curl
            - openssl
            - xml2
            - mesa
