language: r
cache: packages
warnings_are_errors: true

r_packages:
  - curl
  - knitr
  - devtools
  - testthat
  - seqinr
  - foreach
  - doMC
  - tidyverse
  - mclust
  - feature

bioc_required: true
bioc_packages:
   - BiocGenerics
   - Biostrings

matrix:
  include:
    - name: linux-focal-r-release
      os: linux
      dist: focal
      r: release travis_wait 30
      before_install:
        - sudo apt-get update
        - sudo apt-get -y install libcurl4-openssl-dev libssl-dev libxml2-dev pandoc libglu1-mesa-dev libssh2-1-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev libgit2-dev
      before_script:
        - R -e "sessionInfo()"
      install:
    - name: linux-focal-r-devel
      os: linux
      dist: focal
      r: devel travis_wait 30
      before_install:
        - sudo apt-get update
        - sudo apt-get -y install libcurl4-openssl-dev libssl-dev libxml2-dev pandoc libglu1-mesa-dev libssh2-1-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev
      before_script:
        - R -e "sessionInfo()"
    - name: osx-xcode12-r-release
      os: osx
      osx_image: xcode12
      r: release travis_wait 30
      addons:
        homebrew:
          packages:
            - curl
            - openssl
            - xml2
            - mesa
