---
title: "CRBHits Basic Vignette"
author: "Kristian K Ullrich"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{CRBHits Basic Vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

[CRBHits](https://gitlab.gwdg.de/mpievolbio-it/crbhits) is a reimplementation of the Conditional Reciprocal Best Hit algorithm [crb-blast](https://github.com/cboursnell/crb-blast) in R.

1. [Installation](#install)

see also here for the R package pages [https://mpievolbio-it.pages.gwdg.de/crbhits/](https://mpievolbio-it.pages.gwdg.de/crbhits/)

## R specific installation prerequisites

### install packages from [cran](https://cran.r-project.org/web/packages/index.html)

In most cases you need to first install the following system-wide packages to be able to compile the R dependencies.

Ubuntu/Debian

```
sudo apt-get install libcurl4-openssl-dev libssl-dev libxml2-dev
```

CentOS

```
sudo yum install libcurl-devel openssl-devel libxml2-devel
```

- [devtools](https://cran.r-project.org/web/packages/devtools/index.html)
- [testthat](https://cran.r-project.org/web/packages/testthat/index.html)
- [seqinr](https://cran.r-project.org/web/packages/seqinr/index.html)
- [foreach](https://cran.r-project.org/web/packages/foreach/index.html)
- [doMC](https://cran.r-project.org/web/packages/doMC/index.html)
- [magrittr](https://cran.r-project.org/web/packages/magrittr/index.html)

```
install.packages("devtools")
install.packages("testthat")
install.packages("seqinr")
install.packages("foreach")
install.packages("doMC")
install.packages("magrittr")
```

### install packages from [Bioconductor](https://www.bioconductor.org/)

```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("Biostrings")
```

### install [CRBHits](https://gitlab.gwdg.de/mpievolbio-it/crbhits)

```
library(devtools)
install_gitlab("mpievolbio-it/crbhits", host = "https://gitlab.gwdg.de")
#install_github("kullrich/CRBHits", build_vignettes = TRUE, dependencies = FALSE)
```

## External tools installation prerequisites

The source code for both prerequisites (LAST, KaKs_Calculator2.0) are forked within [CRBHits](https://gitlab.gwdg.de/mpievolbio-it/crbhits). 

- [LAST](http://last.cbrc.jp/) [http://last.cbrc.jp/last-1060.zip](http://last.cbrc.jp/last-1060.zip)

```
#setwd(paste0(find.package("CRBHits"), "/extdata/"))
#system(paste0("unzip last-1060.zip"))
#setwd(paste0(find.package("CRBHits"), "/extdata/last-1060/"))
## see more installation iformation here, if make fails
## last-install-help: http://last.cbrc.jp/doc/last.html
#system("make")
make.last()
```

- [KaKs_Calculator2.0](https://sourceforge.net/projects/kakscalculator2/files/KaKs_Calculator2.0.tar.gz/download)

```
#setwd(paste0(find.package("CRBHits"), "/extdata/"))
#system(paste0("tar -xvf KaKs_Calculator2.0.tar.gz"))
#setwd(paste0(find.package("CRBHits"), "/extdata/KaKs_Calculator2.0/src/"))
#system("make clean")
#system("make")
make.KaKs_Calculator2()
```

If you would like to install the latest version of both tools, you need to download the source code and compile again.

2. [Reciprocal best hit pairs](#rbhpairs)



3. [Conditional reciprocal best hit pairs](#crbhpairs)
